// Generated by CoffeeScript 1.6.3
var backboneLib, underscore, unitInfo, unitInfoInstance;

backboneLib = require('./lib/backbone-min');

underscore = require('./lib/underscore-min');

unitInfo = backboneLib.Backbone.Model.extend({
  "default": {
    modelNumber: 'defaultModel',
    serialNumber: 'defaultSerial'
  }
});

unitInfoInstance = new unitInfo();

console.log('Unit Info' + unitInfoInstance.toJSON());
